# Generated by Django 6.0.2 on 2026-09-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=30)),
                ('property_location', models.CharField(max_length=200)),
                ('campaign_package', models.CharField(choices=[('starter', 'Starter Boost (3 Days - 5,000+ Reach)'), ('pro', 'Pro Growth (7 Days - 20,000+ Reach - Recommended)'), ('ultra', 'Ultra Reach (15 Days - 50,000+ Reach + Social Ads)')], default='pro', max_length=20)),
                ('property_note', models.TextField(blank=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign Request',
                'verbose_name_plural': 'Campaign Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
