# Generated by Django 6.0.2 on 2026-09-25 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Optional message/note sent to the user upon contacting.'),
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who requested the advertising campaign', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
